In [2]:
# Importing Libraries
from matplotlib import colors 
from matplotlib.ticker import PercentFormatter 
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd
from scipy.integrate import solve_ivp
import scipy.optimize as opt


In [14]:
# Creates the growth curve

def monod_eq(um, Ks, Y_xs, time):

    def f(t,y):
        A = y[0]
        B = y[1]
        
        dA_dt = A*um*B/((Ks)+B)
        dB_dt = -dA_dt/Y_xs

        return np.array([dA_dt, dB_dt]) 


    t_span = np.array([0,time])
    times = np.linspace(t_span[0], t_span[1], time)

    y0 = np.array([5,100])
    
    soln = solve_ivp(f, t_span, y0, t_eval = times)
    t = soln.t
    A = soln.y[0]
    B = soln.y[1]

    df = pd.DataFrame(data = A,columns = ['A'] )
    df['B'] = B

    return df

def squared_error(par):
    print(par)
    um = par[0]
    Ks = par[1]
    Y_xs = par[2]
    
    
    training_set = monod_eq(um, Ks, Y_xs)
    test_set = total_flowrate
    
    
    sse = 0
    for i,row in training_set.iterrows():
        sse = sse + (training_set.iloc[(i,0)] - test_set.iloc[(i,0)])**2
    print(sse)
        
    return sse
        
        
        
    

## Optimization Function

In [72]:
# Optimization Funciton 

um = 2.95100090e+02
Ks = 2.17613850e+08
Y_xs = 1.60176588e+01*0.97
par_all = [um, Ks, Y_xs]

dataset = total_flowrate

# Test points are defined as monod equaion
testpoints = monod_eq(um, Ks, Y_xs)

s_error = lambda p: squared_error(p)
solution = opt.minimize(s_error, par_all, method = 'Nelder-Mead', tol = 1e-6)

[2.9510009e+02 2.1761385e+08 1.5537129e+01]
522300403.11052144
[3.09855095e+02 2.17613850e+08 1.55371290e+01]
752754656.8317357
[2.95100090e+02 2.28494542e+08 1.55371290e+01]
736426965.0030167
[2.95100090e+02 2.17613850e+08 1.63139855e+01]
748288889.1481757
[2.80345085e+02 2.24867645e+08 1.60550333e+01]
1061001921.4261694
[3.02477592e+02 2.19427299e+08 1.56666051e+01]
576316913.6097082
[3.00018425e+02 2.26076611e+08 1.48465900e+01]
746424164.8476259
[2.98788841e+02 2.23960921e+08 1.52134388e+01]
585539199.5306246
[3.02477592e+02 2.12173504e+08 1.54076530e+01]
724665417.7718511
[3.00633217e+02 2.16253763e+08 1.54400220e+01]
570346849.5454242
[3.00018425e+02 2.11569021e+08 1.58823986e+01]
864517953.3350958
[2.99096237e+02 2.20862946e+08 1.53806788e+01]
522231841.5870906
[2.94075437e+02 2.17059741e+08 1.52386148e+01]
534691026.02130973
[2.91547959e+02 2.20770594e+08 1.53309264e+01]
612382673.4421164
[2.98361902e+02 2.17382971e+08 1.54127481e+01]
528873363.8581823
[3.00963383e+02 2.2018010

KeyboardInterrupt: 